### PR TITLE
colormath 3.0.0: fix networkx dependency

### PR DESCRIPTION
**Pull request by mbargull**
The missing version constraint on `networkx` caused https://github.com/bioconda/bioconda-recipes/issues/7290 (`multiqc 1.3` depends on `<2` which contradicts `>=2.0` for `colormath` in `setuptools`' requirements).

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @mbargull - I got the same AppVeyor failure. From reading the docs, it sounds like the `bat` files shouldn't be required, yet here the tests are failing because they're not there. I chose to just ignore the failures and merge anyway, but perhaps you know a better solution?

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
@ewels: You can either re-render manually with `conda smithy rerender` or just use the bot as I did in the comment above, see https://conda-forge.org/docs/webservice.html for other automatic services.

We could also turn this into a `noarch: python` package, I think? If you think that would be fine, you can add a comment with "`@conda-forge-admin`, please add noarch: python" to let the bot do its thing.

**Comment by mbargull** [comment]
Oh, wow... By putting `@conda-forge-admin` into a code block, I wanted to **not** trigger the bot... Well, that didn't pan out as I thought it would...

So new proposal: If you think this package should be `noarch: python`, then go ahead and merge. If not, we can just revert the last two commits

**Comment by ewels** [comment]
Hah, amazing. That is some clever magic :)

I'm sure that you know better than me, so I'm sure that making it `noarch: python` is fine. According to [this documentation](https://conda-forge.org/docs/meta.html#building-noarch-packages) it sounds like it should be at least, so I'm happy.

Phil

**Comment by ewels** [comment]
Many thanks for your help with this @mbargull!

**Comment by mbargull** [comment]
You're very welcome!

> clever magic

Yep, the people that set up `conda-smity` and those bots did an amazing job!

**Pull request merged**
